
## Server Properties
server.port: 5000

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
## sakila ( MySQL sample Data )
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:frameworkdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8
    username: sa
    password: password
    sql-script-encoding: UTF-8
    # Initialize the datasource with available DDL and DML scripts
    initialization-mode: always

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    ## Hibernate Properties
    hibernate:
      ddl-auto: create
    database-platform: H2

  ## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  ## Spring Ehcache configuration file
  cache:
    jcache:
      config: classpath:ehcache.xml

## Hibernate Logging
logging:
  level:
    org.hibernate: DEBUG

## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
